### PR TITLE
Added neetoChat Email templates

### PR DESCRIPTION
**Pull request by ghousemohamed**

### CODE REVIEW

**Comment by vinay0x** [comment]
@ghousemohamed @neerajdotname Is keeping the app-specific emails in the gem the best way to go? What I had in my mind was that the gem will provide the building blocks and the host application can use the blocks for building the mail. 

The trouble I'm seeing with this approach is that, when a change needs to be made to the mailer, it has to be done at the gem level. And testing the mailers on local becomes very difficult if the entire mailer is part of the gem. 

Let me know what you guys think.

**Comment by ghousemohamed** [comment]
@vinay The idea behind the app like approach here is that all email templates will reside in the gem and the content for that will given by the client app. In the future if we want to change the branding of the email templates then we can change here and push the change and all the apps using the gem would have changed the branding. Also this allows for reuse of templates. Supposing an email template is reused in 2 different apps then making a change in here would reflect in both the apps.
And for testing, I'm thinking since the templates here are pure html, we can test it without the gem also using the browser.

**Comment by vinay0x** [comment]
@ghousemohamed For branding purposes, we are giving them the components for building it right? For eg, we can define that the logo will be positioned a particular way in the Header partial exported by the gem or that the body of the email will be 16px and 500 font-weight. If there's a branding change, we can modify the elements/blocks to reflect it. I thought of the neeto-email gem just like how neeto-ui would work. We can give them smaller elements like buttons and compound elements like headers. 

> And for testing, I'm thinking since the templates here are pure html, we can test it without the gem also using the browser.

Sorry for not being clear the previous time. Let's say I'm adding a few new fields to the chat transcript email. I make the necessary backend changes and I want to edit the email template to add these new fields to show up in a certain style. If the gem is just giving the host applications building blocks, I can make the necessary changes in the email template that is using the blocks. My question is, how would someone go about making the change and testing it if the entirety of the email is in a separate gem? Or what if they want to add a new template and it's very basic. Please let me know if I'm missing any of the ideas.

I strongly suggest not keeping host-specific emails in the gem. But again, we can have a discussion on this if needed.
@neerajdotname Can you please chime in here with your thoughts?

**Comment by ghousemohamed** [comment]
@vinay0x We have built the components in the folder here at `app/views/shared` and they can used to construct the email template in the client app. But we are constructing it here in the gem itself. Ok got it, we should just be constructing using these templates in the client app and not in the gem itself.

**Comment by neerajdotname** [comment]
I agree with @ghousemohamed. This is working this is the right way to build it rather than over-engineer things from day one. I don't see any issue with the current design. Once it becomes the issue we will tackle it. It's clear that whatever changes happen tomorrow for today the current design is the right thing for today.

**Comment by neerajdotname** [comment]
@vinay0x I still think you are over thinking it. In the current state this is getting work done. Let's move on until it is an issue.

**Pull request merged**
